# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9097492e9c29ecd8ba2555dcf62b574e"
application_url = "https://next-demo2-lyart.vercel.app/"
embedded = true
name = "AAXIS Streamline Dev APP"
handle = "aaxis-streamline-dev-app"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "b2b-accelerator.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/app/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/app/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/app/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,write_cart_transforms,customer_read_companies,customer_read_customers,customer_read_draft_orders,customer_read_locations,customer_read_orders,customer_write_companies,customer_write_customers,customer_write_locations,customer_write_orders,read_content,read_customers,read_discounts,read_draft_orders,read_orders,read_products,write_content,write_customers,write_discounts,write_draft_orders,write_orders,write_products,read_themes,write_themes,read_payment_terms,unauthenticated_read_product_listings,unauthenticated_read_product_pickup_locations,unauthenticated_read_product_pickup_locations,unauthenticated_read_product_tags,unauthenticated_read_selling_plans,unauthenticated_read_product_inventory,write_payment_terms,read_payment_terms,read_publications,read_shipping,read_inventory,read_locations"

[auth]
redirect_urls = [
  "https://next-demo2-lyart.vercel.app/auth/callback",
  "https://next-demo2-lyart.vercel.app/auth/shopify/callback",
  "https://next-demo2-lyart.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://next-demo2-lyart.vercel.app/apps/customer-account"
subpath = "customer-account"
prefix = "apps"

[pos]
embedded = false
