export const QUERY_ALL_SHOPPING_LISTS = "QUERY_ALL_SHOPPING_LISTS";
export const QUERY_SHOPPING_LIST_BY_ID = "QUERY_SHOPPING_LIST_BY_ID";
export const QUERY_SHOPPING_LIST_DETAIL = "QUERY_SHOPPING_LIST_DETAIL";
export const QUERY_SHIP_TO_LOCATION_LIST = "QUERY_SHIP_TO_LOCATION_LIST";
export const QUERY_USER_LIST = "QUERY_USER_LIST";
export const QUERY_CUSTOMER_PARTNER_NUMBER_BY_SKU =
  "QUERY_CUSTOMER_PARTNER_NUMBER_BY_SKU";
export const PRODUCTS_BY_IDS = "PRODUCTS_BY_IDS";
export const PRODUCT_PRICE = "PRODUCT_PRICE";
export const QUERY_USER_DETAILS = "QUERY_USER_DETAILS";
export const QUERY_ROLES = "QUERY_ROLES";
export const CART_GET_AJAX = "CART_GET_AJAX";
export const CART_ADD_TO_CART_AJAX = "CART_ADD_TO_CART_AJAX";
export const QUERY_CUSTOMER_INFORMATION = "QUERY_CUSTOMER_INFORMATION";

export const QUERY_DRAFT_ORDERS = "QUERY_DRAFT_ORDERS";
export const QUERY_DRAFT_ORDER_DETAILS = "QUERY_DRAFT_ORDER_DETAILS";

export const QUERY_ORDER_HISTORY = "QUERY_ORDER_HISTORY";
export const QUERY_ORDER_DETAIL = "QUERY_ORDER_DETAIL";
export const QUERY_ADMIN_PORTAL_CUSTOMER_CODE_LIST =
  "QUERY_ADMIN_PORTAL_CUSTOMER_CODE_LIST";
export const QUERY_ADMIN_PORTAL_COMPANY_LIST =
  "QUERY_ADMIN_PORTAL_COMPANY_LIST";
export const QUERY_ADMIN_PORTAL_COMPANY_AND_COMPANY_LOCATIONS =
  "QUERY_ADMIN_PORTAL_COMPANY_AND_COMPANY_LOCATIONS";
export const QUERY_ADMIN_PORTAL_SHOP = "QUERY_ADMIN_PORTAL_SHOP";

export const QUERY_SHOPPING_LIST_AGGREGATION =
  "QUERY_SHOPPING_LIST_AGGREGATION";

export const QUERY_PRODUCT_VARIANTS_BY_API = "QUERY_PRODUCT_VARIANTS_BY_API";
export const QUERY_PRODUCT_PRICE_BY_VARIANTS =
  "QUERY_PRODUCT_PRICE_BY_VARIANTS";

export const QUERY_SHOP_SETTINGS = "QUERY_SHOP_SETTINGS";

export const QUERY_ADMIN_PORTAL_QUOTES_LIST = "QUERY_ADMIN_PORTAL_QUOTES_LIST";

export const QUERY_QUOTES_LIST = "QUERY_QUOTES_LIST";

export const QUERY_QUOTES_BY_ID = "QUERY_QUOTES_BY_ID";

export const QUERY_ADMIN_PORTAL_QUOTE_DETAILS =
  "QUERY_ADMIN_PORTAL_QUOTE_DETAILS";

export const QUERY_SHIPPING_METHODS = "QUERY_SHIPPING_METHODS";

export const QUERY_ALL_SUBSCRIPTION_ORDERS = "QUERY_ALL_SUBSCRIPTION_ORDERS";
export const QUERY_SUBSCRIPTION_ORDER_BY_ID = "QUERY_SUBSCRIPTION_ORDER_BY_ID";
export const QUERY_SUBSCRIPTION_ORDERS_HISTORY =
  "QUERY_SUBSCRIPTION_ORDERS_HISTORY";

export const QUERY_RECOMMENDED_PRODUCTS = "QUERY_RECOMMENDED_PRODUCTS";

export const FEATURE_LIST = "FEATURE_LIST";

export const QUERY_ALL_SUBSCRIPTION_PLANS = "QUERY_ALL_SUBSCRIPTION_PLANS";
export const QUERY_SUBSCRIPTION_PLAN_BY_ID = "QUERY_SUBSCRIPTION_PLAN_BY_ID";
export const CHECK_IS_VALID_SUBSCRIPTION_PLAN =
  "CHECK_IS_VALID_SUBSCRIPTION_PLAN";
