api_version = "2025-01"

[[extensions]]
name = "t:name"
handle = "cart-transform-quote"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.cart-transform.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
  watch = [ "src/**/*.ts" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
